---
resources:
- name: concourse-onboard
  type: git
  source:
    uri: https://github.com/tvs/concourse-onboard.git
    branch: master
    git_config:
      - name: core.bigFileThreshold
        value: 10m
    disable_ci_skip: true

jobs:
- name: fetch-source
  plan:
  - get: concourse-onboard
    params: {depth: 100}
  - task: annoy
    file: concourse-onboard/ci/annoy.yml
